name: "Workflow to build Java project"

on:
  push

jobs:
  build:
    # Github runs it on Linux runner
    runs-on: ubuntu-latest

    steps:
      - name: "Step 1: Checkout the code"
        uses: actions/checkout@v3
     
      - name: "Step 2: Set Java"
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: "Step 3: Build with Maven"
        run: mvn -ntp clean package
        
      # https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
      - name: "Step 4: Build docker image"
        uses: docker/build-push-action@v4
        with:
          tags: ${{ github.action_repository }}:latest
          # The default working directory on the runner for steps
          context: ${{ github.workspace }}

        
